import { Dimension, Dimensions } from '../common';
import { BasePartition } from './common';
import { MetricNameAggregation } from './namespace-partition';

/**
 * aggregated raw metric items, generated by the metric watcher and aggregates every minute.
 *
 * @deprecated
 */
export interface NamespaceDimensionsPartition extends BasePartition {
  readonly by?: 'namespace';
  readonly _v?: 1;

  readonly namespace: string;
  // as for now, we keep the Dimensions type for backward compatibiltiy because some clients still log the Object dimensions.
  // and the aggregator needs to understand them.
  readonly dimensions?: Dimension[] | Dimensions; // aggregated metrics have the same dimensions.

  readonly aggregationPeriod: number; // in ms.
  readonly startTimestamp: number;

  readonly metricItems: MetricNameAggregation[];
}
